name: fire
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libzlib=1.3.1
  - openssl=3.0.18
  - python=3.13.9
  - python_abi=3.13
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - earthengine-api==1.6.15
      - geopandas==1.1.1
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.5.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.72.0
      - httplib2==0.31.0
      - idna==3.11
      - meteostat==1.7.6
      - numpy==2.3.4
      - packaging==25.0
      - pandas==2.3.3
      - pip==25.3
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyogrio==0.11.1
      - pyparsing==3.2.5
      - pyproj==3.7.2
      - pytz==2025.2
      - requests==2.32.5
      - rsa==4.9.1
      - shapely==2.1.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
prefix: C:\Users\tsiry\anaconda3\envs\fire
